###############################Sujeto s01#######################################
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s01Guino1.png ../pyfaces/gallery 54 2
###############################Sujeto s02#######################################
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s02Durmiendo1.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s02LuzCentral1.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s02Normal4.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s02Sorpresa5.png ../pyfaces/gallery 54 2
###############################Sujeto s03#######################################
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s03Durmiendo1.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s03Feliz2.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s03Normal4.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s03Triste3.png ../pyfaces/gallery 54 2
###############################Sujeto s04#######################################
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s04Guino1.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzCentral5.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s04LuzDerecha4.png ../pyfaces/gallery 54 2
###############################Sujeto s05#######################################
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s05Normal5.png ../pyfaces/gallery 54 2
###############################Sujeto s06#######################################
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s06Durmiendo1.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s06Normal5.png ../pyfaces/gallery 54 2
###############################Sujeto s07#######################################
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s07Feliz1.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s07Guino2.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s07Normal3.png ../pyfaces/gallery 54 2
###############################Sujeto s08#######################################
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s08LuzCentral4.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s08Normal5.png ../pyfaces/gallery 54 2
###############################Sujeto s09#######################################
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s09LuzCentral2.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s09Normal1.png ../pyfaces/gallery 54 2
##############################Sujeto s010#######################################
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s10LuzCentral1.png ../pyfaces/gallery 54 2
###############################Sujeto s11#######################################
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s11Durmiendo4.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s11LuzDerecha4.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s11Sorpresa2.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s11Triste1.png ../pyfaces/gallery 54 2
###############################Sujeto s12#######################################
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s12Feliz2.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s12Guino2.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s12LuzIzquierda1.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s12Normal1.png ../pyfaces/gallery 54 2
###############################Sujeto s13#######################################
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s13Feliz1.png ../pyfaces/gallery 54 2
##############################Sujeto s14#######################################
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s14Sorpresa2.png ../pyfaces/gallery 54 2
###############################Sujeto s16#######################################
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s16LuzIzquierda3.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s16Sorpresa1.png ../pyfaces/gallery 54 2
###############################Sujeto s18#######################################
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s18LuzCentral1.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s18Triste2.png ../pyfaces/gallery 54 2
###############################Sujeto 19#######################################
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s19Durmiendo4.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s19Sorpresa4.png ../pyfaces/gallery 54 2
###############################Sujeto s20#######################################
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 1 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 2 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 3 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 4 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 5 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 6 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 12 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 18 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 24 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 30 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 36 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 42 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 48 2
python pyfacesdemo/ ../pyfaces/probes/s20Durmiendo1.png ../pyfaces/gallery 54 2
python pyfacesdemo/ ../pyfaces/probes/s20LuzIzquierda3.png ../pyfaces/gallery 54 2

